#!/bin/bash
# Send the pending prompt from .ai-workflow/context/PROMPT.md to the Builder terminal
# Works with both Gemini and Claude CLI

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTEXT_DIR="$(dirname "$SCRIPT_DIR")/context"

PROMPT_FILE="$CONTEXT_DIR/PROMPT.md"
RELAY_MODE_FILE="$CONTEXT_DIR/RELAY_MODE"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

# Check if prompt file exists
if [ ! -f "$PROMPT_FILE" ]; then
    echo -e "${RED}❌ No prompt file found at $PROMPT_FILE${NC}"
    exit 1
fi

# Extract the prompt (everything between the --- markers, excluding the header)
PROMPT=$(awk '/^---$/{p=!p; next} p && !/^## How to Send/' "$PROMPT_FILE" | sed '/^$/d' | head -50)

if [ -z "$PROMPT" ] || [ "$PROMPT" = "(No prompt pending)" ]; then
    echo -e "${YELLOW}⚠️  No prompt pending. Ask Copilot to create one first.${NC}"
    exit 1
fi

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}📤 Sending Prompt to Builder${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Prompt:${NC}"
echo "$PROMPT"
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Copy to clipboard if available
if command -v xclip &> /dev/null; then
    echo "$PROMPT" | xclip -selection clipboard
    echo -e "${GREEN}✓ Copied to clipboard!${NC}"
elif command -v pbcopy &> /dev/null; then
    echo "$PROMPT" | pbcopy
    echo -e "${GREEN}✓ Copied to clipboard!${NC}"
fi

echo ""
echo -e "${YELLOW}Paste this into your Builder terminal (Gemini/Claude)${NC}"
echo ""

# Clear the prompt file after sending
cat > "$PROMPT_FILE" << 'EOF'
# Pending Prompt for Builder

> **Status:** Sent
> **Generated by:** Copilot
> **Timestamp:** (cleared)

---

(No prompt pending)

---

## How to Send

```bash
# Option 1: Copy the prompt above and paste into Builder terminal

# Option 2: Use the send script
./scripts/send-prompt.sh

# Option 3: Switch to auto mode (prompts send automatically)
echo "auto" > .context/RELAY_MODE
```
EOF

echo -e "${GREEN}✓ Prompt file cleared${NC}"
